### ISSUE TITLE
파일 수정 날짜 비교 코드 테스트

### ISSUE THREAD

**Issue by thsgustlr0318** [luxlunae15/Project2#10]
timecmp 코드 테스트

**Comment by thsgustlr0318** [comment]
두 파일의 수정 시간이 같을 때
![20200519_224112](https://user-images.githubusercontent.com/61684785/82333691-0748d280-9a22-11ea-9b80-5d2250aff58f.png)

text1이 text2보다 최근에 수정되었을 때
![20200519_224135](https://user-images.githubusercontent.com/61684785/82333695-07e16900-9a22-11ea-83ed-e40ec582d30e.png)

text2가 text1보다 최근에 수정되었을 때
![20200519_224221](https://user-images.githubusercontent.com/61684785/82333697-0879ff80-9a22-11ea-8ded-4d082c54d4f3.png)

**Comment by YeChanSong** [comment]
고생하셨습니다.

**Comment by luxlunae15** [comment]
확인
