### ISSUE TITLE
파일 정보 가져오기 코드 작성

### ISSUE THREAD

**Issue by YeChanSong** [luxlunae15/Project2#11]
filestat1, filestat2 함수 작성

**Comment by YeChanSong** [comment]
void filestat1(){
    stat("text1", &stat1);
}
void filestat2(){
    stat("text2", &stat2); 
}
파일 정보는 stat함수를 통해 stat 구조체에 경로에 있는 파일의 정보를 가져옵니다.

**Comment by luxlunae15** [comment]
Well Play

**Comment by thsgustlr0318** [comment]
잘 쓸게요
