### ISSUE TITLE
파일 시간 정보 가져오기 코드 작성

### ISSUE THREAD

**Issue by YeChanSong** [luxlunae15/Project2#12]
filetime1, filetime2 코드 작성

**Comment by YeChanSong** [comment]
void filetime1(){
    time1 = localtime(&stat1.st_mtime);
}
void filetime2(){
    time2 = localtime(&stat2.st_mtime);
}
파일의 정보가 담긴 stat 구조체에서 st_mtime을 localtime의 매개변수로 넘겨줍니다.

**Comment by luxlunae15** [comment]
굿 잡

**Comment by thsgustlr0318** [comment]
오 좋아요~
