### ISSUE TITLE
sizecmp 기반 기술 조사

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project2#14]
파일의 크기를 비교하는 sizecmp 구현에 사용될 함수 조사입니다

**Comment by luxlunae15** [comment]
int stat(const char *path, struct stat *buf) 함수를 사용할 경우
dev_id, inode, mode, link수, uid, gid, size, block수, atime, mtime, ctime 등에 대한 정보를 받아옵니다.

파일의 size를 비교하기 위해서는 위의 정보들 중에서 size 정보를 사용하여 파일의 크기를 비교하는 데 사용합니다. 파일 size는 off_t 타입으로 st_size변수에 저장이 되어 있습니다.

**Comment by YeChanSong** [comment]
확인했습니다.

**Comment by thsgustlr0318** [comment]
잘 활용하겠습니다..
