### ISSUE TITLE
sizecmp 코드 리뷰

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project2#16]
구현된 sizecmp 함수에 대한 코드 리뷰입니다.

**Comment by luxlunae15** [comment]
![1](https://user-images.githubusercontent.com/61813922/82324136-1c1e6980-9a14-11ea-8e0f-2524bf968a0d.JPG)

![2](https://user-images.githubusercontent.com/61813922/82324325-6acc0380-9a14-11ea-89c6-b99b0ba7c7a5.JPG)

![3](https://user-images.githubusercontent.com/61813922/82324340-70294e00-9a14-11ea-8773-658f41d082d1.JPG)

위와 같은 결과가 나왔습니다

**Comment by YeChanSong** [comment]
확인했습니다.

**Comment by thsgustlr0318** [comment]
좋네요
