### ISSUE TITLE
blockcmp 기반 기술 조사

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project2#17]
파일의 block 수를 비교하는 blockcmp구현에 사용될 함수 조사입니다

**Comment by luxlunae15** [comment]
int stat(const char *path, struct stat *buf) 함수를 사용할 경우
dev_id, inode, mode, link수, uid, gid, size, block수, atime, mtime, ctime 등에 대한 정보를 받아옵니다.

파일의 블락 수는 blkcnt_t 타입의 변수 st_blocks에 저장되므로 이를 비교하여 블록 수가 많은 파일을 출력합니다.

**Comment by YeChanSong** [comment]
이해했습니다.

**Comment by thsgustlr0318** [comment]
좋아요~
