### ISSUE TITLE
blockcmp 코드 작성

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project2#18]
blockcmp 함수에 대한 코드 작성입니다.

**Comment by luxlunae15** [comment]
stat1에 text1의 정보가 저장되어 있고,
stat2에 text2의 정보가 저장되어 있으므로

void blockcmp(){
if(stat1.st_blocks > stat2.st_blocks)
printf("text1 is bigger\n");
else if (stat1.st_blocks < stat2.st_blocks)
printf("text2 is bigger\n");
else
printf("sizes are equal\n");
}

와 같이 작성하였습니다.

**Comment by YeChanSong** [comment]
확인했습니다.

**Comment by thsgustlr0318** [comment]
네 좋습니다
