### ISSUE TITLE
blockcmp 코드 리뷰

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project2#19]
구현된 blockcmp 함수에 대한 코드 리뷰입니다.

**Comment by luxlunae15** [comment]
![1](https://user-images.githubusercontent.com/61813922/82324398-8800d200-9a14-11ea-9d34-651954a6f977.JPG)

![2](https://user-images.githubusercontent.com/61813922/82324399-8931ff00-9a14-11ea-8df9-fe81181fd43d.JPG)

![3](https://user-images.githubusercontent.com/61813922/82324402-8931ff00-9a14-11ea-8ede-6f5c03e9ac96.JPG)

와 같은 결과가 나왔습니다.

**Comment by YeChanSong** [comment]
확인했습니다 :)

**Comment by thsgustlr0318** [comment]
제대로 동작되는 것 확인하였습니다.
