### ISSUE TITLE
파일 시간 정보 가져오기 기반 기술 조사

### ISSUE THREAD

**Issue by YeChanSong** [luxlunae15/Project2#21]
함수 구현에 사용될 함수 기반 조사입니다.

**Comment by YeChanSong** [comment]
struct tm *localtime( const time_t *timer ) 함수를 사용할 경우, timer가 가리키는 time_t값을 가지고 tm구조체를 초기화시킨다.

tm 구조체에는 아래와 같은 형태로 구성되어 있습니다.
struct tm { 
int tm_sec; /* 초 - [0～61] */ 
int tm_min; /* 분 - [0～59] */ 
int tm_hour; /* 시 - [0～23] */ 
int tm_mday; /* 일 - [1～31] */
int tm_mon; /* 월 - [0～11] */ 
int tm_year; /* 1900부터의 년 */ 
int tm_wday; /* 일요일부터의 요일 - [0～6] */ 
int tm_yday; /* 년초부터의 통산 일수 - [0～365] */ 
int tm_isdst; /* 서머 타임이 유효하면 양수, 유효하지 않으면 0, 불명이면 음수*/ };

**Comment by luxlunae15** [comment]
정보 감사합니다.

**Comment by thsgustlr0318** [comment]
잘 활용하겠습니다~
