### ISSUE TITLE
파일 정보 가져오기 기반 기술 조사

### ISSUE THREAD

**Issue by YeChanSong** [luxlunae15/Project2#22]
함수 구현에 사용될 기술 조사입니다.

**Comment by YeChanSong** [comment]
int stat(const char *path, struct stat *buf) 함수를 통해 파일의 정보를 가져올 수 있습니다.
이때, path로 지정해준 경로의 파일의 정보를 buf가 가리키는 stat 구조체에 담습니다.
stat 구조체에는 time_t st_mtime 변수가 들어있어서 이후 파일 시간 정보를 가져올 때 
localtime의 매개변수로 줄 수 있습니다.

**Comment by thsgustlr0318** [comment]
감사합니다.

**Comment by luxlunae15** [comment]
좋은 정보 감사합니다.
