### ISSUE TITLE
파일 시간 정보 가져오기 코드 리뷰

### ISSUE THREAD

**Issue by YeChanSong** [luxlunae15/Project2#23]
코드를 구현한 이후 리뷰입니다.

**Comment by YeChanSong** [comment]
![image](https://user-images.githubusercontent.com/54590290/82321964-b2509080-9a10-11ea-8860-194b564bbeb4.png)

위와 같이 시간정보를 담은 time변수를 asctime에 매개변수로 넘겨주면 시간이 잘 나옴을 볼 수 있습니다.

**Comment by thsgustlr0318** [comment]
네 좋네요

**Comment by luxlunae15** [comment]
잘하셨습니다.
