### ISSUE TITLE
파일 정보 가져오기 코드 리뷰

### ISSUE THREAD

**Issue by YeChanSong** [luxlunae15/Project2#24]
함수 구현 이후 코드 리뷰입니다.

**Comment by YeChanSong** [comment]
![image](https://user-images.githubusercontent.com/54590290/82322116-f17ee180-9a10-11ea-8d54-b7bacbcedf4e.png)
위와 같이 text1, text2의 inode 정보를 정상적으로 가져온 것을 볼 수 있습니다.

**Comment by thsgustlr0318** [comment]
긋긋긋~

**Comment by luxlunae15** [comment]
잘하셨습니다.
