### ISSUE TITLE
파일 수정 날짜 비교 코드 작성

### ISSUE THREAD

**Issue by thsgustlr0318** [luxlunae15/Project2#4]
파일 수정 날짜 비교 코드 (datecmp) 작성하기

**Comment by thsgustlr0318** [comment]
파일 수정 시간을 읽어들일 때, 이전 파일의 시간이 덮어씌어지는 문제점이 발생하여
따로 변수를 만들어서 해결하였습니다.
void datecmp(){
	printf("date compare\n");
	int mon2 = time2->tm_mon, day2 = time2->tm_mday;
	time1 = localtime(&stat1.st_mtime);
	int mon1 = time1->tm_mon, day1 = time1->tm_mday;
	if(mon1 == mon2){
		if(day1 == day2){
			printf("same date\n\n");
		}
		else if(day1 > day2){
			printf("text1 is early\n\n");
		}
		else{
			printf("text2 is early\n\n");
		}
	}
	else if (mon1 > mon2){
		printf("text1 is early\n\n");
	}
	else{
		printf("text2 is early\n\n");
	}  
    
}

**Comment by YeChanSong** [comment]
확인했습니다.

**Comment by luxlunae15** [comment]
문제를 해결하여 다행입니다.
