### ISSUE TITLE
Readme 작성

### ISSUE THREAD

**Issue by luxlunae15** [luxlunae15/Project2#5]
튜토리얼에 맞게 Readme 작성

**Comment by luxlunae15** [comment]
Assignment2
팀장

2015722093 이종학(luxlunae15)

팀원

2015722027 손현식(thsgustlr0318)

2015722032 송예찬(YeChanSong)



와 같이 작성하였음

**Comment by YeChanSong** [comment]
확인했습니다.

**Comment by thsgustlr0318** [comment]
네 확인하였습니다.
