### ISSUE TITLE
파일 수정 날짜 비교 코드 테스트

### ISSUE THREAD

**Issue by thsgustlr0318** [luxlunae15/Project2#6]
파일 수정 날짜 비교 코드 테스트 수행하기.

**Comment by thsgustlr0318** [comment]
수정 날짜가 같은 경우
![20200519_183233](https://user-images.githubusercontent.com/61684785/82333227-61956380-9a21-11ea-8422-0a3b96b55fd7.png)

text2가 text1보다 최근에 변경된 경우
![20200519_183309](https://user-images.githubusercontent.com/61684785/82333232-622dfa00-9a21-11ea-9a39-a4218789afa0.png)

text1이 text2보다 최근에 변경된 경우
![20200519_183545](https://user-images.githubusercontent.com/61684785/82333235-62c69080-9a21-11ea-99ca-855dff2d7a42.png)

**Comment by YeChanSong** [comment]
확인했습니다.

**Comment by luxlunae15** [comment]
확인
