### ISSUE TITLE
파일 수정 시간 비교를 위한 기반 기술 조사

### ISSUE THREAD

**Issue by thsgustlr0318** [luxlunae15/Project2#8]
파일 수정 시간 비교를 위한 stat, time 관련 조사

**Comment by thsgustlr0318** [comment]
stat함수는 파일의 정보를 읽어오는 함수이다.
함수의 인자는 다음과 같다.

struct stat { 
dev_t st_dev; /*ID of device containing file */ 
ino_t st_ino; /inode number/ 
mode_t st_mode; /protection/ 
nlink_t st_nlink; /number of hard links/ 
uid_t st_uid; /user ID of owner/ 
gid_t st_gid; /group ID of owner/ 
dev_t st_rdev; /device ID (if special file)/ 
off_t st_size; /total size, in byte/ 
blksize_t st_blksize; /blocksize for file system I/O/ 
blkcnt_t st_blocks; /number of 512B blocks allocated/ 
time_t; st_atime; /time of last access/ 
time_t; st_mtime; /time of last modification/ 
time_t st_xtime; /time of last status change/};

리눅스 시스템에서는 기본 타임 서비스에서 카운트한 time_t 값을 반환하는 time 함수를 제공한다.
이 함수에서 얻을 수 있는 값은 시스템의 부호화된 time_t 형 달력 시간이다. 시간을 얻을 수 없는 경우는 -1을 반환한다.
localtime() 함수는 년/월/일 등의 값을 나타내는 멤버가 있는 tm 구조체에 대한 포인터를 반환한다. tm 구조체는 다음과 같이 선언되어 있다
struct tm {
int tm_sec; /* 초 - [0～61] /
int tm_min; / 분 - [0～59] /
int tm_hour; / 시 - [0～23] /
int tm_mday; / 일 - [1～31] /
int tm_mon; / 월 - [0～11] /
int tm_year; / 1900부터의 년 /
int tm_wday; / 일요일부터의 요일 - [0～6] /
int tm_yday; / 년초부터의 통산 일수 - [0～365] /
int tm_isdst; / 서머 타임이 유효하면 양수, 유효하지 않으면 0, 불명이면 음수*/
};

**Comment by YeChanSong** [comment]
고생하셨습니다.

**Comment by luxlunae15** [comment]
정보 감사 합니다.
