### ISSUE TITLE
파일 수정 시간 비교 코드 작성

### ISSUE THREAD

**Issue by thsgustlr0318** [luxlunae15/Project2#9]
timecmp 코드 작성

**Comment by thsgustlr0318** [comment]
파일 수정 시간을 읽어들일 때, 이전 파일의 시간이 덮어씌어지는 문제점이 발생하여
따로 변수를 만들어서 해결하였습니다.
void timecmp(){
        printf("time compare\n");
        int hour1 = time1->tm_hour, min1 = time1->tm_min;
        time2 = localtime(&stat2.st_mtime);
        int hour2 = time2->tm_hour, min2 = time1->tm_min;
        if(hour1 == hour2){
                if(min1 == min2){
                        printf("same time\n\n");
                }
                else if(min1 > min2){
                        printf("text1 is early\n\n");
                }
                else{
                        printf("text2 is early\n\n");
                }
        }
        else if (hour1 > hour2){
                printf("text1 is early\n\n");
        }
        else{
                printf("text2 is early\n\n");
        }

}

**Comment by YeChanSong** [comment]
고생하셨습니다.

**Comment by luxlunae15** [comment]
확인
